# Generated by Django 5.0.4 on 2024-04-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_manager', '0002_manager_alter_client_employer_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('В работе', 'In Work'), ('Не в работе', 'Out-Work'), ('Сделка закрыта', 'Close'), ('Отказ', 'Rejected')], default='Не в работе', max_length=14),
        ),
    ]
